import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'az';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    "nav.home": "Home",
    "nav.routes": "Routes",
    "nav.map": "Map",
    "nav.profile": "Profile",
    "nav.safety": "Safety",
    "nav.services": "Services",
    "nav.community": "Community",
    
    "home.hero.title": "Find Your Path \n In The Mountains",
    "home.hero.subtitle": "Explore the best hiking trails, track your adventures, and connect with a community of nature lovers.",
    "home.hero.explore": "Explore Routes",
    "home.hero.map": "View Map",
    "home.featured.title": "Featured Trails",
    "home.featured.subtitle": "Hand-picked routes for your next weekend adventure.",
    "home.services.title": "Expert Guides & Services",
    "home.services.subtitle": "Enhance your adventure with professional support.",
    "home.discover": "Discover Azerbaijan",
    "home.view_all": "View All",
    "home.view_all_routes": "View All Routes",
    "home.weekly_challenge": "Weekly Challenge",
    "home.challenge_title": "The 5 Peak Challenge",
    "home.challenge_description": "Climb 5 peaks above 2000m this month to earn the exclusive \"Highlander\" badge and a spot on the leaderboard.",
    "home.joined_challenge": "Joined ✓",
    "home.join_challenge": "Join Challenge",
    "home.leaderboard": "Leaderboard",
    "home.you": "You",
    
    "routes.title": "Explore Routes",
    "routes.subtitle": "Find your next adventure among Azerbaijan's most beautiful trails.",
    "routes.search": "Search routes or regions...",
    "routes.filter.difficulty": "Difficulty",
    "routes.filter.region": "Region",
    "routes.filter.distance": "Max Distance",
    "routes.empty": "No routes found",
    "routes.any_difficulty": "Any Difficulty",
    "routes.any_region": "Any Region",
    "routes.reset": "Reset",
    "routes.clear_filters": "Clear Filters",
    "routes.empty_desc": "Try adjusting your search or filters to find what you're looking for.",
    "routes.difficulty.easy": "Easy",
    "routes.difficulty.medium": "Medium",
    "routes.difficulty.hard": "Hard",
    
    "services.title": "Services & Rentals",
    "services.subtitle": "Hire guides, babysitters, or rent equipment for your trip.",
    "services.tab.guides": "Guides",
    "services.tab.babysitters": "Babysitters",
    "services.tab.equipment": "Equipment",
    "services.book": "Book Now",
    "services.per_day": "/ day",
    "services.available": "Available",
    "services.booked": "Booked",
    "services.verified": "Verified Professional",
    
    "community.title": "Community Hikes",
    "community.subtitle": "Join scheduled group hikes and meet fellow adventurers.",
    "community.create": "Create Hike",
    "community.join": "Join Hike",
    "community.full": "Full",
    "community.joined": "Joined",
    "community.participants": "participants",
    "community.hosted_by": "Hosted by",
    
    "profile.badges": "Badges",
    "profile.history": "Hike History",
    "profile.hikes": "Hikes",
    "profile.kilometers": "Kilometers",
    "profile.elevation": "Elevation",
    "profile.earned": "Earned",
    "profile.progress": "progress",
    "profile.nature_enthusiast": "Nature enthusiast & Weekend explorer",
    "profile.completed": "Completed",
    "profile.no_hikes": "No completed hikes yet. Go explore!",
    "profile.guest_mode": "Guest Mode",
    "profile.guest_warning": "You are viewing as a guest. Log in to save your progress and earn badges, or you'll lose your data.",
    "profile.guest_account": "Guest Account - Log in to save your progress",
    "profile.guest_account_name": "Guest Account",
    "profile.login_button": "Log In Now",
    "profile.login_to_earn_badges": "Log in to start earning badges and track your progress!",
    
    "route.distance": "Distance",
    "route.elevation": "Elevation",
    "route.duration": "Duration",
    "route.weather": "Weather",
    "route.about": "About the Trail",
    "route.map": "Trail Map",
    "route.location": "Location",
    "route.get_directions": "Get Directions",
    "route.join_group": "Join a Group",
    "route.group_planning": "groups are planning to hike this trail this weekend.",
    "route.saturday_hike": "Saturday Morning Hike",
    "route.spots_left": "spots left",
    "route.join": "Join Group",
    "route.not_found": "Route not found",
    "route.mark_completed": "Mark as Completed",
    "route.completed": "Completed",
    "route.located_in": "Located in the",
    "route.region": "region.",
    
    "safety.title": "Safety First",
    "safety.subtitle": "The mountains are beautiful but unpredictable. Follow these essential tips to ensure a safe and enjoyable adventure in Azerbaijan's wilderness.",
    "safety.emergency": "Emergency Contacts",
    "safety.emergency_desc": "In case of emergency, call these numbers immediately. Cell service may be limited in remote areas.",
    "safety.general": "General Emergency",
    "safety.ambulance": "Ambulance",
    
    "community.loading": "Loading...",
    "community.no_hikes": "No community hikes available yet. Be the first to create one!",
    "community.title_label": "Hike Title",
    "community.route": "Route",
    "community.select_route": "Select a route",
    "community.date": "Date",
    "community.time": "Time",
    "community.description": "Description (optional)",
    "community.max_participants": "Max Participants",
    "community.cancel": "Cancel",
    "community.error": "Hata",
    "community.loading_error": "Hike'lar yüklenirken bir hata oluştu",
    "community.login_required": "Giriş Gerekli",
    "community.login_desc": "Bu işlem için giriş yapmanız gerekiyor",
    "community.join_success": "Katıldınız! 🥾",
    "community.create_login": "Hike oluşturmak için giriş yapmanız gerekiyor",
    "community.missing_fields": "Eksik Alanlar",
    "community.fill_fields": "Lütfen tüm gerekli alanları doldurun",
    
    "services.filters": "Filters",
    "services.search": "Search services...",
    "services.price_range": "Price Range (AZN/day)",
    "services.min_rating": "Minimum Rating",
    "services.any": "Any",
    "services.empty": "No services found",
    "services.empty_desc": "Try adjusting your search or filters to find what you're looking for.",
    
    "service.not_found": "Service not found",
    "service.description": "Description",
    "service.details": "Details",
    "service.verified_professional": "Verified Professional",
    "service.verified_desc": "Identity and certification checked",
    "service.flexible_cancellation": "Flexible Cancellation",
    "service.cancellation_desc": "Free cancellation up to 24h before",
    "service.not_charged": "You won't be charged yet",
    "service.booking_sent": "Booking Request Sent!",
    "service.booking_desc": "We've sent a request for",
    "service.confirmation": "You will receive a confirmation soon.",
    
    "map.explorer": "Map Explorer",
    "map.tap_marker": "Tap a marker to view details",
    
    "login.title": "Giriş Yap",
    "login.signup": "Kayıt Ol",
    "login.desc": "Hesabınıza giriş yapın",
    "login.signup_desc": "Yeni hesap oluşturun",
    "login.username": "Kullanıcı Adı *",
    "login.password": "Şifre *",
    "login.password_placeholder": "Şifrenizi girin",
    "login.name": "İsim *",
    "login.name_placeholder": "Adınız Soyadınız",
    "login.phone_number": "Telefon Numarası",
    "login.phone_placeholder": "+994 XX XXX XX XX",
    "login.email": "E-posta (İsteğe Bağlı)",
    "login.email_placeholder": "ornek@email.com",
    "login.loading": "Yükleniyor...",
    "login.success": "Giriş Başarılı! 🎉",
    "login.signup_success": "Kayıt Başarılı! 🎉",
    "login.no_account": "Hesabınız yok mu? Kayıt olun",
    "login.has_account": "Zaten hesabınız var mı? Giriş yapın",
    "login.error": "Hata",
    
    "footer.desc": "Azerbaijan's premier hiking companion. Discover hidden trails, track your progress, and connect with nature.",
    "footer.explore": "Explore",
    "footer.popular_routes": "Popular Routes",
    "footer.map_view": "Map View",
    "footer.safety_tips": "Safety Tips",
    "footer.community": "Community",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.cookies": "Cookie Policy",
    
    "footer.rights": "© 2025 ZippyGO. All rights reserved.",
    "footer.made_with": "Designed by Light team with ♥️ in Azerbaijan"
  },
  az: {
    "nav.home": "Ana Səhifə",
    "nav.routes": "Marşrutlar",
    "nav.map": "Xəritə",
    "nav.profile": "Profil",
    "nav.safety": "Təhlükəsizlik",
    "nav.services": "Xidmətlər",
    "nav.community": "İcma",
    
    "home.hero.title": "Dağlarda Öz \n Yolunu Tap",
    "home.hero.subtitle": "Ən yaxşı yürüş yollarını kəşf edin, macəralarınızı izləyin və təbiətsevərlər icmasına qoşulun.",
    "home.hero.explore": "Marşrutları Kəşf Et",
    "home.hero.map": "Xəritəyə Bax",
    "home.featured.title": "Seçilmiş Yollar",
    "home.featured.subtitle": "Növbəti həftəsonu macəranız üçün seçilmiş marşrutlar.",
    "home.services.title": "Ekspert Bələdçilər və Xidmətlər",
    "home.services.subtitle": "Macəranızı peşəkar dəstək ilə zənginləşdirin.",
    "home.discover": "Azərbaycanı Kəşf Edin",
    "home.view_all": "Hamısına Bax",
    "home.view_all_routes": "Bütün Marşrutlara Bax",
    "home.weekly_challenge": "Həftəlik Çağırış",
    "home.challenge_title": "5 Zirvə Çağırışı",
    "home.challenge_description": "Bu ay 2000 metrdən yuxarı 5 zirvəyə qalxaraq eksklüziv \"Dağlı\" nişanını və liderlər cədvəlində yer qazanın.",
    "home.joined_challenge": "Qoşuldu ✓",
    "home.join_challenge": "Çağırışa Qoşul",
    "home.leaderboard": "Liderlər Cədvəli",
    "home.you": "Siz",
    
    "routes.title": "Marşrutları Kəşf Et",
    "routes.subtitle": "Azərbaycanın ən gözəl cığırları arasında növbəti macəranızı tapın.",
    "routes.search": "Marşrut və ya region axtar...",
    "routes.filter.difficulty": "Çətinlik",
    "routes.filter.region": "Region",
    "routes.filter.distance": "Maks Məsafə",
    "routes.empty": "Marşrut tapılmadı",
    "routes.any_difficulty": "Hər Hansı Çətinlik",
    "routes.any_region": "Hər Hansı Region",
    "routes.reset": "Sıfırla",
    "routes.clear_filters": "Filterləri Təmizlə",
    "routes.empty_desc": "Axtarış və ya filterləri dəyişdirərək axtardığınızı tapmağa çalışın.",
    "routes.difficulty.easy": "Asan",
    "routes.difficulty.medium": "Orta",
    "routes.difficulty.hard": "Çətin",
    
    "services.title": "Xidmətlər və İcarə",
    "services.subtitle": "Səfəriniz üçün bələdçi, dayə tutun və ya avadanlıq icarəyə götürün.",
    "services.tab.guides": "Bələdçilər",
    "services.tab.babysitters": "Dayələr",
    "services.tab.equipment": "Avadanlıq",
    "services.book": "İndi Bron Et",
    "services.per_day": "/ gün",
    "services.available": "Mövcuddur",
    "services.booked": "Məşğuldur",
    "services.verified": "Təsdiqlənmiş Peşəkar",
    
    "community.title": "İcma Yürüşləri",
    "community.subtitle": "Planlaşdırılmış qrup yürüşlərinə qoşulun və digər macəraçılarla tanış olun.",
    "community.create": "Yürüş Yarat",
    "community.join": "Qoşul",
    "community.full": "Dolu",
    "community.joined": "Qoşuldu",
    "community.participants": "iştirakçı",
    "community.hosted_by": "Təşkilatçı:",
    
    "profile.badges": "Nişanlar",
    "profile.history": "Yürüş Tarixçəsi",
    "profile.hikes": "Yürüşlər",
    "profile.kilometers": "Kilometr",
    "profile.elevation": "Hündürlük",
    "profile.earned": "Qazanılıb",
    "profile.progress": "irəliləyiş",
    "profile.nature_enthusiast": "Təbiətsevər və Həftəsonu kəşfçisi",
    "profile.completed": "Tamamlandı",
    "profile.no_hikes": "Hələ tamamlanmış yürüş yoxdur. Kəşf etməyə başla!",
    "profile.guest_mode": "Qonaq Rejimi",
    "profile.guest_warning": "Qonaq kimi baxırsınız. İrəliləyişinizi qorumaq və nişanlar qazanmaq üçün giriş edin, əks halda məlumatlarınız itəcək.",
    "profile.guest_account": "Qonaq Hesabı - İrəliləyişinizi saxlamaq üçün giriş edin",
    "profile.guest_account_name": "Qonaq Hesabı",
    "profile.login_button": "İndi Giriş Et",
    "profile.login_to_earn_badges": "Nişanlar qazanmağa və irəliləyişinizi izləməyə başlamaq üçün giriş edin!",
    
    "route.distance": "Məsafə",
    "route.elevation": "Hündürlük",
    "route.duration": "Müddət",
    "route.weather": "Hava",
    "route.about": "Yol Haqqında",
    "route.map": "Yol Xəritəsi",
    "route.location": "Yerləşmə",
    "route.get_directions": "İstiqamət Al",
    "route.join_group": "Qrupa Qoşul",
    "route.group_planning": "qrup bu həftəsonu bu yolda yürüş planlaşdırır.",
    "route.saturday_hike": "Şənbə Səhər Yürüşü",
    "route.spots_left": "yer qalıb",
    "route.join": "Qrupa Qoşul",
    "route.not_found": "Marşrut tapılmadı",
    "route.mark_completed": "Tamamlandı Olaraq İşarələ",
    "route.completed": "Tamamlandı",
    "route.located_in": "Yerləşir",
    "route.region": "regionunda.",
    
    "safety.title": "Təhlükəsizlik Əvvəldir",
    "safety.subtitle": "Dağlar gözəldir, amma proqnozlaşdırıla bilməz. Azərbaycanın vəhşi təbiətində təhlükəsiz və zövqlü macəra üçün bu vacib məsləhətlərə əməl edin.",
    "safety.emergency": "Təcili Yardım Əlaqələri",
    "safety.emergency_desc": "Təcili vəziyyətdə dərhal bu nömrələrə zəng edin. Uzaq bölgələrdə mobil rabitə məhdud ola bilər.",
    "safety.general": "Ümumi Təcili Yardım",
    "safety.ambulance": "Tibbi Yardım",
    
    "community.loading": "Yüklənir...",
    "community.no_hikes": "Hələ icma yürüşü yoxdur. İlkini yaratmaq sizdə!",
    "community.title_label": "Yürüş Başlığı",
    "community.route": "Marşrut",
    "community.select_route": "Marşrut seçin",
    "community.date": "Tarix",
    "community.time": "Vaxt",
    "community.description": "Təsvir (istəyə bağlı)",
    "community.max_participants": "Maks İştirakçı",
    "community.cancel": "Ləğv Et",
    "community.error": "Xəta",
    "community.loading_error": "Yürüşlər yüklənərkən xəta baş verdi",
    "community.login_required": "Giriş Tələb Olunur",
    "community.login_desc": "Bu əməliyyat üçün giriş etməlisiniz",
    "community.join_success": "Qoşuldunuz! 🥾",
    "community.create_login": "Yürüş yaratmaq üçün giriş etməlisiniz",
    "community.missing_fields": "Çatışmayan Sahələr",
    "community.fill_fields": "Zəhmət olmasa bütün tələb olunan sahələri doldurun",
    
    "services.search": "Xidmətlər axtar...",
    "services.filters": "Filterlər",
    "services.price_range": "Qiymət Aralığı (AZN/gün)",
    "services.min_rating": "Minimum Reytinq",
    "services.any": "Hər Hansı",
    "services.empty": "Xidmət tapılmadı",
    "services.empty_desc": "Axtarış və ya filterləri dəyişdirərək axtardığınızı tapmağa çalışın.",
    
    "service.not_found": "Xidmət tapılmadı",
    "service.description": "Təsvir",
    "service.details": "Detallar",
    "service.verified_professional": "Təsdiqlənmiş Peşəkar",
    "service.verified_desc": "Şəxsiyyət və sertifikat yoxlanılıb",
    "service.flexible_cancellation": "Çevik Ləğv",
    "service.cancellation_desc": "24 saat əvvələ qədər pulsuz ləğv",
    "service.not_charged": "Hələ ödəniş alınmayacaq",
    "service.booking_sent": "Bron Sorğusu Göndərildi!",
    "service.booking_desc": "üçün sorğu göndərdik",
    "service.confirmation": "Tezliklə təsdiq alacaqsınız.",
    
    "map.explorer": "Xəritə Kəşfçisi",
    "map.tap_marker": "Detalları görmək üçün markerə toxunun",
    
    "login.title": "Giriş Yap",
    "login.signup": "Qeydiyyatdan Keç",
    "login.desc": "Hesabınıza giriş edin",
    "login.signup_desc": "Yeni hesab yaradın",
    "login.username": "İstifadəçi Adı *",
    "login.password": "Şifrə *",
    "login.password_placeholder": "Şifrənizi daxil edin",
    "login.name": "Ad *",
    "login.name_placeholder": "Adınız Soyadınız",
    "login.phone_number": "Telefon Nömrəsi",
    "login.phone_placeholder": "+994 XX XXX XX XX",
    "login.email": "E-poçt (İstəyə Bağlı)",
    "login.email_placeholder": "nümunə@email.com",
    "login.loading": "Yüklənir...",
    "login.success": "Giriş Uğurlu! 🎉",
    "login.signup_success": "Qeydiyyat Uğurlu! 🎉",
    "login.no_account": "Hesabınız yoxdur? Qeydiyyatdan keçin",
    "login.has_account": "Artıq hesabınız varmı? Giriş edin",
    "login.error": "Xəta",
    
    "footer.desc": "Azərbaycanın əsas yürüş yoldaşı. Gizli yolları kəşf edin, irəliləyişinizi izləyin və təbiətlə əlaqə qurun.",
    "footer.explore": "Kəşf Et",
    "footer.popular_routes": "Məşhur Marşrutlar",
    "footer.map_view": "Xəritə Görünüşü",
    "footer.safety_tips": "Təhlükəsizlik Məsləhətləri",
    "footer.community": "İcma",
    "footer.legal": "Hüquqi",
    "footer.privacy": "Məxfilik Siyasəti",
    "footer.terms": "Xidmət Şərtləri",
    "footer.cookies": "Cookie Siyasəti",
    
    "footer.rights": "© 2025 ZippyGO. Bütün hüquqlar qorunur.",
    "footer.made_with": "  Light team hazırladı"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
